# Generated by Django 2.2.6 on 2020-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='role', to='system.Permission', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user', to='system.RoleModel', verbose_name='角色'),
        ),
    ]
