# Generated by Django 2.2.6 on 2020-12-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20201221_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='菜单等级'),
        ),
    ]
